Per query credentials
back4app/Parse-SDK-JS-Multi-Tenant pull request #1
Opened 2019-01-23 01:42 UTC by davimacedo

2019-01-23 20:13 UTC, douglasmuraoka requested changes
Encontrei só um detalhe no RESTController.

2019-01-23 20:13 UTC, douglasmuraoka commented on src/RESTController.js
>        if (CoreManager.get('MASTER_KEY')) {
Aqui também não seria necessário o options?

2019-01-24 05:10 UTC, davimacedo commented on src/RESTController.js
>        if (CoreManager.get('MASTER_KEY')) {
Feito. Da mais uma olhada pls?

2019-01-24 13:57 UTC, douglasmuraoka approved these changes

2019-01-24 13:58 UTC, merged